#!/usr/bin/env bash
# FIXME: delete this line #### https://github.com/jones77/shlintro for more info
declare -r __basename="$(      basename "${BASH_SOURCE[0]}" )"
declare -r __dirname="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
set -o errexit && set -o nounset && set -o pipefail && : # set -o xtrace
exit_fail() { echo "$__basename: Error: $@" && echo && usage && exit 1; }
usage() {
    # FIXME: Better description
    # FIXME: Remove "[FILES]..." if you're using strict argument parsing
    cat <<USAGE
Usage: $__basename [OPTION]... [FILES]...

  FIXME: Update this description describing what the script does

Example:
  $__basename -e example a b c

Options:
  -h, --help            Show this help and exit
  -e, --example ARG     Print example "ARG" information
USAGE
};
# TODO: specify script arguments
declare -r getopt_args=$(getopt -s bash \
    --options     "the:" \
    --longoptions "help,example:" \
    --name ${__basename} -- "$@") && eval set -- "${getopt_args}"
while :
do
    case $1 in
	-h|--help) usage && exit 0 ;;
	--) exit_fail "Unexpected arguments: $@" ;;  # strict argument parsing
	# --) shift && break ;;  # [FILES]... argument parsing
        -e|--example)
            shift && echo "The example option's argument is: $1"
	    ;;
	*)  exit_fail "Bad arguments: $1" ;;
   esac && shift
done
while (( $# ))  # [FILES]... argument parsing
do
    echo "Do something with: $1"

    shift
done
